<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <DataPortVersion>1.0.1-ci2878897099</DataPortVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AwesomeAssertions" Version="9.4.0" />
    <PackageVersion Include="AwesomeAssertions.Analyzers" Version="9.0.8" />
    <PackageVersion Include="libplctag" Version="1.5.2" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.4.1" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="ViciOne.Suite.DataPort" Version="$(DataPortVersion)" />
    <PackageVersion Include="ViciOne.Suite.DataPort.Extensions" Version="$(DataPortVersion)" />
    <PackageVersion Include="ViciOne.Suite.DataPort.Extensions.Testing" Version="$(DataPortVersion)" />
    <PackageVersion Include="ViciOne.Tree.Builder" Version="3.0.0" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>
</Project>