<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ViciOne.Suite.DataPort.AllenBradley.Legacy.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions"/>
    <PackageReference Include="AwesomeAssertions.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage"/>
    <PackageReference Include="NSubstitute"/>
    <PackageReference Include="ViciOne.Suite.DataPort.Extensions.Testing"/>
    <PackageReference Include="xunit.v3.mtp-v2"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AllenBradley.Legacy\AllenBradley.Legacy.csproj"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
    <Using Include="AwesomeAssertions"/>
    <AssemblyAttribute Include="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute"/>
  </ItemGroup>

</Project>
